version: '3.8'

services:
  # selenium-hub:
  #   image: selenium/standalone-chrome
  #   container_name: selenium-hub
  #   ports:
  #     - "4444:4444"
  #   networks:
  #     - app-network
  fastapi-app:
    build:
      context: ./Backend/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - Backend/.env
    networks:
      - app-network

  react-app:
    build:
      context: ./my-monitor-app/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./my-monitor-app:/app
      - /app/node_modules
    depends_on:
      - fastapi-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
